HotelProject/Models/ImageRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HotelProject.Models
{
    public class ImageRoom
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public byte[] Image { get; set; }
        public int RoomId { get; set; }
        public virtual Room Room { get; set; }
    }
}

HotelProject/Controllers/ImageRoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HotelProject.DAL;
using HotelProject.Models;

namespace HotelProject.Controllers
{
    public class ImageRoomsController : Controller
    {
        public int UploadImageInDataBase(HttpPostedFileBase file, ImageRoom imageRoom)
        {
            imageRoom.Image = ConvertToBytes(file);
            var Content = new ImageRoom
            {
                Title = imageRoom.Title,
                Image = imageRoom.Image,
                RoomId = imageRoom.RoomId

            };
            db.ImageRoom.Add(Content);
            int i = db.SaveChanges();
            if (i == 1)
            {
                return 1;
            }
            else
            {
                return 0;
            }
        }
        public byte[] ConvertToBytes(HttpPostedFileBase image)
        {
            byte[] imageBytes = null;
            BinaryReader reader = new BinaryReader(image.InputStream);
            imageBytes = reader.ReadBytes((int)image.ContentLength);
            return imageBytes;
        }
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }
        public byte[] GetImageFromDataBase(int Id)
        {
            var q = from temp in db.ImageRoom where temp.ID == Id select temp.Image;
            byte[] cover = q.First();
            return cover;
        }
        private HotelContext db = new HotelContext();


        // GET: ImageRooms
        public ActionResult Index()
        {
           var imageRoom = db.ImageRoom.Include(i => i.Room);
           return View(imageRoom.ToList());

           /* var content = db.ImageRoom.Select(s => new
            {
                s.ID,
                s.Title,
                s.Image,
                s.RoomId,
            });
            List<ImageRoom> imageRoom = content.Select(item => new ImageRoom()
            {
                ID = item.ID,
                Title = item.Title,
                Image = item.Image,
                RoomId = item.RoomId,
            }).ToList();
            return View(imageRoom.ToList());*/
        }
        public ActionResult RoomImage()
        {
            var imageRoom = db.ImageRoom.Include(i => i.Room);
            return View(imageRoom.ToList());
        }        /*       {
                   if (Room_id == null)
                   {
                       return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                   }


                   ImageRoom imageRoom = db.ImageRoom.FirstOrDefault(room => room.RoomId == Room_id);

                   if (imageRoom == null)
                   {
                       return HttpNotFound();
                   }

                   return View("ImageRoom/ImgRoom");
               }*/

        // GET: ImageRooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageRoom imageRoom = db.ImageRoom.Find(id);
            if (imageRoom == null)
            {
                return HttpNotFound();
            }
            return View(imageRoom);
        }

        // GET: ImageRooms/Create
        public ActionResult Create()
        {
            ViewBag.RoomId = new SelectList(db.Room, "ID", "Name");
            return View();
        }

        // POST: ImageRooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RoomId")] ImageRoom imageRoom)
        {
            HttpPostedFileBase file = Request.Files["ImageData"];
            ImageRoomsController service = new ImageRoomsController();
            int i = service.UploadImageInDataBase(file, imageRoom);
            if (i == 1 && ModelState.IsValid)
            {
                db.ImageRoom.Add(imageRoom);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.RoomId = new SelectList(db.Room, "ID", "Name", imageRoom.RoomId);
            return View(imageRoom);
        }

        // GET: ImageRooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageRoom imageRoom = db.ImageRoom.Find(id);
            if (imageRoom == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoomId = new SelectList(db.Room, "ID", "Name", imageRoom.RoomId);
            return View(imageRoom);
        }

        // POST: ImageRooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RoomId")] ImageRoom imageRoom)
        {
            if (ModelState.IsValid)
            {
                db.Entry(imageRoom).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoomId = new SelectList(db.Room, "ID", "Name", imageRoom.RoomId);
            return View(imageRoom);
        }

        // GET: ImageRooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageRoom imageRoom = db.ImageRoom.Find(id);
            if (imageRoom == null)
            {
                return HttpNotFound();
            }
            return View(imageRoom);
        }

        // POST: ImageRooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ImageRoom imageRoom = db.ImageRoom.Find(id);
            db.ImageRoom.Remove(imageRoom);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HotelProject/Views/ImageRooms/Create.cshtml
@model HotelProject.Models.ImageRoom

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ImageRooms", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ImageRoom</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RoomId, "RoomId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
            @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HotelProject/Views/ImageRooms/Delete.cshtml
@model HotelProject.Models.ImageRoom

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ImageRoom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Room.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HotelProject/Views/ImageRooms/Details.cshtml
@model HotelProject.Models.ImageRoom

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ImageRoom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Room.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Room.Name)
        </dd>
        <dd>
            <img src="@Url.Action("RetrieveImage", "ImageRooms", new { id = Model.ID })" alt="" height="100" width="200" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HotelProject/Views/ImageRooms/Edit.cshtml
@model HotelProject.Models.ImageRoom

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ImageRoom</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.RoomId, "RoomId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HotelProject/Views/ImageRooms/Index.cshtml
@model IEnumerable<HotelProject.Models.ImageRoom>

@{
    ViewBag.Title = "Index";
}
@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Room.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Room.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <img src="@Url.Action("RetrieveImage", "ImageRooms", new { id = item.ID })" alt="" style="max-height: 300px; max-width: 600px;" />
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

HotelProject/Views/ImageRooms/RoomImage.cshtml
@model IEnumerable<HotelProject.Models.ImageRoom>


@{
    ViewBag.Title = "Index";
}
@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Room.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Where(r => r.RoomId == Convert.ToInt32(Request.QueryString["Roomid"])))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Room.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <img src="@Url.Action("RetrieveImage", "ImageRooms", new { id = item.ID })" alt="" style="max-height: 300px; max-width: 600px;" />
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

    @if (!Model.Any(r => r.RoomId == Convert.ToInt32(Request.QueryString["Roomid"])))
    {
        <tr>
            <td colspan="4">
                <p>No image for this room.</p>
            </td>
        </tr>
    }



</table>